### ISSUE TITLE
When I run xmltv.exe tv_grab_na_dd i get encoding="ISO-8859-1" I need UTF-8

### ISSUE THREAD

**Issue by Oumpa31** [mattiash/xmltv#3]
I finally figured out how to use this program and was hoping it would fix my issues with the xmltv file I got from an iptv place. But when i run it i keep getting encoding="ISO-8859-1" and xTeVe will only read UTF-8 how do i fix this

**Comment by mattiash** [comment]
This repository is just a copy of XMLTV as it looked in CVS 10 years ago. The correct repository today is https://github.com/XMLTV/xmltv I think.
